### PR TITLE
[Component governance] Update Azure.Identity dependency

### PR DESCRIPTION
**Pull request by javiercn**
* Updating the SqlClient version wasn't enough

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]

**Comment by sebastienros** [comment]
Can you share how you get from Azure.Identity to SqlClient?

**Comment by javiercn** [comment]
https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.1.1#dependencies-body-tab

**Comment by sebastienros** [comment]
And? `Microsoft.Data.SqlClient` depends on `Azure.Identity`, bumping `Azure.Identity` won't get a higher SqlClient version. Or did I read the issue wrong and you are not trying to deal with SqlClient in this PR?

**Comment by javiercn** [comment]
@sebastienros I'm trying to deal with the fact that even the highest SqlClient version doesn't have a new enough Azure.identity version. Updating the version for SqlClient on a previous PR wasn't enough.

**Pull request merged**
