### PR TITLE
add support for cgroup v2

### LINKED ISSUE #586: Modern ubuntu distros changed semantics of cgroup, breaking crank's cpuset
Crank depends on cgroup.v1 semantics, which does not work on cgroup.v2 semantics. 

            # on Ubuntu Linux >= 22.04 with cgroup.v2 you must follow this protocol
            # to disable some cgroup.v2 semantics that differ from cgroup.v1
            # crank depends on cgroup.v1 semantics.
            #     https://askubuntu.com/questions/1406329/how-to-run-cgexec-without-sudo-as-current-user-on-ubuntu-22-04-with-cgroups-v2
            # sudo vi /etc/default/grub
            # add to GRUB_CMDLINE_LINUX systemd.unified_cgroup_hierarchy=false
            #   sudo update-grub
            #   sudo reboot
            # You must then run crank as sudo on the linux worker machine, viz:
            #   sudo make MNT=/mnt/root start_load

### PR DESCRIPTION
**Pull request by catcherwong**
close #586 

The following test agent on ubuntu 22.04.

```sh
crank --config ./hello.benchmarks.yml --profile local --scenario hello \
          --application.cpuSet "0" \
          --application.cpuLimitRatio 0.5 \
          --application.framework net6.0
```

image

image

```sh
crank --config ./hello.benchmarks.yml --profile local --scenario hello \
          --application.cpuSet "0-1" \
          --application.cpuLimitRatio 0.5 \
          --application.framework net6.0
```
image

image

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]

**Comment by sebastienros** [comment]
@catcherwong I took the time to test it and wasn't able to get it working. I used the docker file in docker/agent (after changing it to use 8.0-previw base image since otherwise it doesn't have cgroupsv2) and got errors like 

```
[18:53:09 INF] [/] chmod +x /tmp/benchmarks-agent/benchmarks-server-1/ancl3ltc.4a1/src/Benchmarks/published/Benchmarks
[18:53:09 INF] [/] cgcreate -g memory,cpu,cpuset:benchmarks-1-4
[18:53:09 INF] [STDERR] cgcreate: can't create cgroup benchmarks-1-4: Device or resource busy
```

Another colleague tried with crank directly (no docker container) and also had errors.

It's possible that I have broken something when I refactored your PR, can you check again on your side?

**Comment by sebastienros** [comment]
Thanks, yes Robert confirmed he got it working too. So the issue is with the docker container then.

From the one in the repos I applied too changes for it to build at least:
- base from 8.0-preview
- remove the h2load build steps (python dependency issue)

**Comment by sebastienros** [comment]
Spent some more time one it.

I can't add the `memory` controller, it works with `cpu` and `cpuset` though:

```
root@asp-citrine-lin:/sys/fs/cgroup# cat cgroup.subtree_control
cpuset cpu
root@asp-citrine-lin:/sys/fs/cgroup# echo "+memory" > cgroup.subtree_control
bash: echo: write error: Operation not supported
```

So following that I tried to remove any code from `CGroup.cs` and `CGroupV2.cs` which are setting it, and it goes further, but when I start the app using `cgexec` I get another error, though the app started.

```
Job failed at runtime with exit code 96:
[STDERR] cgroup change of group failed
```

Here is the log before it fails:

```
[22:35:57 INF] [/] stat -fc %T /sys/fs/cgroup/
[22:35:57 INF] cgroup2fs
[22:35:57 INF] [/] cgcreate -g cpu,cpuset:benchmarks-1-1
[22:35:57 INF] [/] cgset -r cpu.max="max 100000" benchmarks-1-1
[22:35:57 INF] [/] cgset -r cpuset.cpus=0-15 benchmarks-1-1
[22:35:57 INF] [/] cgset -r cpuset.mems=0 benchmarks-1-1
[22:35:57 INF] Invoking executable: cgexec
[22:35:57 INF]   Arguments: -g cpu,cpuset:benchmarks-1-1 /tmp/benchmarks-agent/benchmarks-server-1/23hofwuc.025/src/Benchmarks/published/Benchmarks  --nonInteractive true --scenarios plaintext --urls http://10.0.0.121:5000 --server Kestrel --kestrelTransport Sockets --protocol http
```

**Comment by catcherwong** [comment]
> I can't add the `memory` controller, it works with `cpu` and `cpuset` though:

I have a test on some machines, the `cgroup.subtree_control` contains `memeory`

image

I'm not sure if this problem has anything to do with the environment or configuration of the machine.

**Pull request merged**
