### PR TITLE
chore: adjust wrk parameters

### PR DESCRIPTION
**Pull request by zhenlei520**
serverPath is not used in wrk and wrk2 configuration

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/crank?pullRequest=373) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/crank?pullRequest=373) before we can accept your contribution.<br/><br/>:x: zhenlei520 [sign now](https://cla.dotnetfoundation.org/dotnet/crank?pullRequest=373)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/crank?pullRequest=373) it.</sub>

**Comment by sebastienros** [comment]
I believe it's the other way around, c.f. https://github.com/aspnet/Benchmarks/blob/main/scenarios/database.benchmarks.yml#L62

**Comment by zhenlei520** [comment]
What is the role of the serverPath variable in wrk.yml and wrk2.yml? I haven't seen it used elsewhere

**Comment by sebastienros** [comment]
None. It used to be the one used a long time ago.

**Comment by zhenlei520** [comment]
> None. It used to be the one used a long time ago.

Okay, if that’s the case, I think it’s more appropriate to change it so as not to cause misunderstandings.

**Comment by zhenlei520** [comment]
> None. It used to be the one used a long time ago.

If I agree with my suggestion, I am happy to initiate Pr again

**Pull request merged**
