### PR TITLE
Add serverScheme support to bombardier.yml

### PR DESCRIPTION
**Pull request by halter73**
This logic is copied verbatim from wrk.yml: 

https://github.com/dotnet/crank/blob/caf293d98ac2b438b6c77dcb54b72c6d9cc67f3e/src/Microsoft.Crank.Jobs.Wrk/wrk.yml#L33

https://github.com/aspnet/Benchmarks/pull/1587 will depend on this.

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]
Note that ultimately we'll remove serverUri altogether.

**Comment by sebastienros** [comment]
I am merging since it's not breaking, and might block you on other prs.

**Comment by halter73** [comment]
Have you seen the following before?

```
[STDERR] Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
[STDERR]    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
[STDERR]    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[STDERR]    at System.Diagnostics.Process.Start()
[STDERR]    at Microsoft.Crank.Jobs.Bombardier.Program.Main(String[] args) in /tmp/benchmarks-agent/benchmarks-server-3869/sysphbha.nrc/src/Program.cs:line 169
[STDERR]    at Microsoft.Crank.Jobs.Bombardier.Program.<Main>(String[] args)
```

**Comment by sebastienros** [comment]
Yes, flaky test on Linux box since a few weeks ago. Doesn't happen on MacOS and Windows, probably the way the environment in the azdo controller is configured. Haven't been able to fix it so far.

It's failing when the bombardier exe is copied locally, then permissions are set, but starting it fails.

**Pull request merged**
